version: "3"

services:
  videolify:
    image: videolify:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: videolify
    hostname: jaideep25/videolify
    volumes:
      - .env:/src/.env:ro
      # These volumes are not mandatory, uncomment if you want to use it
      # - ./app/:/src/app/:ro
      # - ./public/:/src/public/:ro
    restart: unless-stopped
    ports:
      - "3000:3000"
# Uncomment below, remove "ports:" section above and configure labels as
# needed for LetsEncrypt TLS certificates with Traefik.
# See https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/
#   expose:
#     - 3000
#   labels:
#     - "traefik.enable=true"
#     - "traefik.http.routers.jaideep25.rule=Host(`videolify.example.com`)"
#     - "traefik.http.routers.jaideep25.entrypoints=websecure"
#     - "traefik.http.routers.jaideep25.tls.certresolver=myresolver"
#     - "traefik.http.services.jaideep25.loadbalancer.server.port=3000"
